[package]
name = "cubism-demo-rs"
version = "0.1.0"
authors = ["Joshua Ols"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
rand = "0.7.3"
