[package]
name = "cubism-demo-rs"
version = "0.1.0"
authors = ["Joshua Ols <joshua.d.ols@gmail.com>"]
edition = "2021"
rust-version = "1.56"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bevy = { git = 'https://github.com/bevyengine/bevy.git' }
bevy = "0.10.0"
rand = "0.8.5"
ron = "0.8.0"
serde = { version = "1.0.152", features = ["serde_derive"] }
