[package]
name = "cubism-demo-rs"
version = "0.1.0"
authors = ["Joshua Ols <joshua.d.ols@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = 'https://github.com/bevyengine/bevy.git' }
# bevy = "0.5.0"
lazy_static = "1.4.0"
rand = "0.8.3"
