version = "Two"
max_width = 80

format_code_in_doc_comments = true
format_strings = true
wrap_comments = true

use_try_shorthand = true
reorder_impl_items = true

fn_single_line = true
match_block_trailing_comma = true
imports_granularity="Crate"
use_field_init_shorthand = true
