style_edition = "2024"
max_width = 80
use_try_shorthand = true
match_block_trailing_comma = true
use_field_init_shorthand = true

# format_code_in_doc_comments = true
# format_strings = true
# wrap_comments = true
# reorder_impl_items = true
# fn_single_line = true
# imports_granularity="Crate"
