edition="2021"
max_width = 80
use_try_shorthand = true
match_block_trailing_comma = true
use_field_init_shorthand = true

# wrap_comments = true
# format_code_in_doc_comments = true
# format_strings = true
# fn_single_line = true
# imports_layout="HorizontalVertical"
# imports_granularity="Crate"
# group_imports="One"
# reorder_impl_items = true
# version = "Two"
